print True == True
print False == True
print False == False
print 2 == True
print 1 == True
print 0 == True
print 2 == False
print 1 == False
print 0 == False
print True != True
print False != True
print False != False
