
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'Q=\xa2ft0?\x13\xefhb\xf8`\xb6\xa9\xca'
    
_lr_action_items = {'ident':([0,2,4,5,6,7,8,9,10,11,13,15,16,17,18,19,20,21,],[-3,4,-11,13,-10,-4,13,-7,13,13,-11,-5,13,-8,-6,-13,-12,-9,]),'rparen':([6,12,13,14,17,19,20,21,],[-10,19,-11,20,-8,-13,-12,-9,]),'int':([0,2,4,5,6,7,8,9,10,11,13,15,16,17,18,19,20,21,],[-3,6,-11,6,-10,-4,6,-7,6,6,-11,-5,6,-8,-6,-13,-12,-9,]),'equal':([4,],[11,]),'plus':([4,6,9,13,14,15,17,18,19,20,21,],[-11,-10,16,-11,16,16,-8,16,-13,-12,-9,]),'lparen':([0,2,4,5,6,7,8,9,10,11,13,15,16,17,18,19,20,21,],[-3,5,12,5,-10,-4,5,-7,5,5,12,-5,5,-8,-6,-13,-12,-9,]),'print':([0,2,4,6,7,9,13,15,17,18,19,20,21,],[-3,8,-11,-10,-4,-7,-11,-5,-8,-6,-13,-12,-9,]),'minus':([0,2,4,5,6,7,8,9,10,11,13,15,16,17,18,19,20,21,],[-3,10,-11,10,-10,-4,10,-7,10,10,-11,-5,10,-8,-6,-13,-12,-9,]),'$end':([0,1,2,3,4,6,7,9,13,15,17,18,19,20,21,],[-3,0,-2,-1,-11,-10,-4,-7,-11,-5,-8,-6,-13,-12,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([2,5,8,10,11,16,],[9,14,15,17,18,21,]),'program':([0,],[1,]),'simple_statement':([2,],[7,]),'statement':([0,],[2,]),'module':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> module','program',1,'p_program','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',13),
  ('module -> statement','module',1,'p_module','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',17),
  ('statement -> <empty>','statement',0,'p_statement_simple_statement','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',21),
  ('statement -> statement simple_statement','statement',2,'p_statement_statement_simple_statement','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',26),
  ('simple_statement -> print expression','simple_statement',2,'p_simple_statement_print','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',31),
  ('simple_statement -> ident equal expression','simple_statement',3,'p_simple_statement_assign','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',35),
  ('simple_statement -> expression','simple_statement',1,'p_simple_statement_expression','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',39),
  ('expression -> minus expression','expression',2,'p_expression_minus','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',43),
  ('expression -> expression plus expression','expression',3,'p_expression_plus','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',47),
  ('expression -> int','expression',1,'p_expression_num','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',51),
  ('expression -> ident','expression',1,'p_expression_ident','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',55),
  ('expression -> lparen expression rparen','expression',3,'p_expression_paren','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',59),
  ('expression -> ident lparen rparen','expression',3,'p_expression_input','/home/uberblah/Dropbox/School/cc/hw/2/compile/parser.py',63),
]
